config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get 'contacts', to: 'contacts#new', as: :contacts
  post 'contacts', to: 'contacts#create', as: :contacts_input
  get 'contacts/index', to: 'contacts#index', as: :contacts_index
  get 'contacts/:id', to: 'contacts#show', as: :contact
  get 'contacts/:id/edit', to: "contacts#edit", as: :contact_edit
  patch 'contacts/:id', to: 'contacts#update', as: :contact_update
  delete 'contacts/:id', to: 'contacts#destroy', as: :contact_destroy

  get 'devis', to: 'devis#new', as: :devis
  post 'devis', to: 'devis#create', as: :devis_input
  get 'devis/index', to: 'devis#index', as: :devis_index
  get 'devis/:id', to: 'devis#show', as: :devi
  get 'devis/:id/edit', to: 'devis#edit', as: :devi_edit
  patch 'devis/:id', to: 'devis#update', as: :devi_update
  delete 'devis/:id', to: 'devis#destroy', as: :devi_destroy

  get 'reviews', to: 'reviews#new', as: :reviews
  post 'reviews', to: 'reviews#create', as: :reviews_input
  get 'reviews/index', to: 'reviews#index', as: :reviews_index
  get 'reviews/:id', to: 'reviews#show', as: :review
  get 'reviews/:id/edit', to: 'reviews#edit', as: :review_edit
  patch 'reviews/:id', to: 'reviews#update', as: :review_update
  delete 'reviews/:id', to: 'reviews#destroy', as: :review_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  # attr_writer  :nom, :prenom, :email, :phone, :service

  validates :nom, presence: true
  validates :prenom, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :status, inclusion: { in: ["Done", "Pending", "Closed"]}
  validates :service, inclusion: { in: ["Bureaux & Locaux Professionnels", "Copropriétés & Espaces Communs", "Interventions Spécialisées", "Entretien Espaces Verts"]}
end

app/models/devi.rb
class Devi < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :telephone, presence: true
  validates :status, inclusion: { in: ["Done", "Pending", "Closed"]}
  validates :service_demande, presence: true, inclusion: { in: ["Bureaux & Locaux Professionnels", "Copropriétés & Espaces Communs", "Interventions Spécialisées", "Entretien Espaces Verts"]}
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :writer, presence: true
  validates :status, inclusion: { in: ["Lu", "Pending", "Action à prendre"]}
  validates :rating, presence: true, inclusion: { in: (1..5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]

  def index           # GET /contacts/new
    @contacts = Contact.all
  end

  def new           # GET /contacts/new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.status = "Pending"
    if @contact.save
      # @contact.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    redirect_to contacts_index_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_index_path
  end

  private

  def contact_params
    params.require(:contact).permit(:nom, :prenom, :phone, :email, :service, :additional_info, :status)
  end
end

app/controllers/devis_controller.rb
class DevisController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy, :show]

  def index
    @devis = Devi.all
  end

  def new        # GET /devis/new
    @devi = Devi.new
  end

  def create     # POST /devis
    @devi = Devi.new(devi_params)
    @devi.status = "Pending"
    if @devi.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @devi = Devi.find(params[:id])
  end

  def edit
    @devi = Devi.find(params[:id])
  end

  def update
    @devi = Devi.find(params[:id])
    @devi.update(devi_params)
    redirect_to devis_index_path
  end

  def destroy
    @devi = Devi.find(params[:id])
    @devi.destroy
    redirect_to devis_index_path
  end

  private

  def devi_params
    params.require(:devi).permit(:first_name, :last_name, :telephone, :email, :building_address, :nr_de_passages, :nr_d_heures, :cahier_de_charges, :service_demande, :date_rdv, :date_debut_souhaitee, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :dashboard
  def contact
  end

  def about
  end

  def services
  end

  def home
  end

  def dashboard
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy, :show]

  def new
    @review = Review.new
  end

  def index
    @reviews = Review.all
  end

  def create
    @review = Review.new(review_params)
    @review.status = "Pending"
    if @review.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to reviews_index_path
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_index_path
  end

  private

  def review_params
    params.require(:review).permit(:title, :rating, :content, :role, :writer, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devis_helper.rb
module DevisHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div class="container-create">
  <%= render 'shared/navbar' %>
  <div class="card-form">
    <div class="container-submission-request d-flex">
      <h2>Merci d'avoir contacter G&A Cleaning Pro Services!</h2>
  <!--     <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag("color-logo-nobckgrd.png", :alt => "logosample feed", class: "avatar-medium")  %>
      <% end %> -->

      <div class="g-a-contact">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag("color-logo-nobckgrd.png", :alt => "logosample feed", class: "avatar-medium")  %>
        <% end %>
        <h2>G&A Cleaning Pro Services</h2>
        <p>Nr de TVA: 0717771789</p>
        <p>55, Terkluizendreef</p>
        <p>1640 Sint-Genesius-Rode</p>
        <p>0485/13.03.38</p>
        <p>info@gacleaningproservices.com</p>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/contacts/edit.html.erb
<div class="container-all" id="id-container-all">
  <%= render 'shared/navbar' %>
  <div class="card-form">
    <h1>Demande de Contact nr. <%= @contact.id %></h1>
    <div class="card-inner d-flex justify-content-center align-items-center">
      <div class="form d-flex">
        <%= simple_form_for(@contact) do |f| %>
            <div class="card-info-prestations">
              Prénom:<br>
              <%= f.input :prenom, label: false %>
            </div>
            <div class="card-info-prestations">
              Nom:<br>
              <%= f.input :nom, label: false%>
            </div>
            <div class="card-info-prestations">
                Téléphone:<br>
              <%= f.input :phone, label: false%>
            </div>
            <div class="card-info-prestations">
              Email:<br>
              <%= f.input :email, label: false  %>
            </div>
            <div class="card-info-prestations">
              Service sélectionné<br>
              <%= f.input :service, label: false, collection: ["Bureaux & Locaux Professionnels", "Copropriétés & Espaces Communs", "Interventions Spécialisées", "Entretien Espaces Verts"]  %></input>
            </div>
            <div class="card-info-prestations">
              Informations complémentaires:<br>
              <%= f.input :additional_info, label: 'Info complémentaires', label: false, as: :text%>
            </div>
            Statut<br>
            <%= f.input :status, label: false , collection: ["Done", "Pending", "Closed"]%>

          <%= f.button :submit, 'Mettre à jour', id: "btn-ghost-form"%>
        <% end %>
      </div>
    </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/contacts/index.html.erb
<div class="container-all-dashboard" id="id-container-all">
  <%= render 'shared/navbar' %>
  <div class="container-index-dashboard">
  <div class="card-form-dashboard">

    <div class="card-table">
      <h1>Demandes de Contact</h1>
      <table style="width:100%">
        <tr class="col-name">
          <th>Status</th>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Email</th>
          <th>Téléphone</th>
          <th>Service</th>
          <th>Infos Complémentaires</th>
          <th></th>
          <th></th>
<!--           <th>Statut</th>
          <th>Mettre à Jous</th>
          <th>Eliminer</th> -->
        </tr>
        <% @contacts.each do |c|%>
          <tr>
            <td><% if c.status == "Pending"%>
              <%= "⏸" %>
            <% elsif c.status == "Done" %>
             <%= "✔️" %>
            <% else  %>
              <%=  "❌"%>
            <% end %>
            </td>
            <td><%= c.nom %></td>
            <td><%= c.prenom %></td>
            <td><%= c.email %></td>
            <td><%= c.phone %></td>
            <td><%= c.service %></td>
            <td><%= c.additional_info %></td>
            <td><%= link_to contact_path(c.id) do %>
              <i class="fas fa-info-circle", id='info'></i>
            <% end %></td>
            <td><%= link_to contact_destroy_path(c.id), method: :delete, data: { confirm: "Est-vous sûr?" } do %>
                  <i class="fa fa-trash", id="trash"></i>
                <% end %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/contacts/show.html.erb
<div class="container-all-dashboard" id="id-container-all">
  <%= render 'shared/navbar' %>
    <div class="container-index-dashboard">
   <div class="card-form">
      <h1>Contact Details</h1>
      <table style="width:100%">
        <tr class="col-name">
          <td>Status</td><td><%= @contact.status %></td>
        </tr>
        <tr class="col-name">
          <td>Nom</td><td><%= @contact.nom %></td>
        </tr>
        <tr class="col-name">
          <td>Prénom</td><td><%= @contact.prenom %></td>
        </tr>
        <tr class="col-name">
          <td>Email</td><td><%= @contact.email %></td>
        </tr>
        <tr class="col-name">
          <td>Téléphone</td><td><%= @contact.phone %></td>
        </tr>
        <tr class="col-name">
          <td>Service</td><td><%= @contact.service %></td>
        </tr>
        <tr class="col-name">
          <td>Autres détails</th><td><%= @contact.additional_info %></td>
        </tr>
      </table>
      <div class="icons d-flex">
      <%= link_to contact_edit_path do %>
        <i class="far fa-edit" id="update"></i>
      <% end %>
      <%= link_to contacts_index_path do %>
        <i class="fas fa-times" id="close"></i>
        <% end %>
      </div>
</div>
    </div>
  <%= render 'shared/footer' %>
</div>

app/views/devis/index.html.erb
<div class="container-all-dashboard" id="id-container-all">
  <%= render 'shared/navbar' %>
  <div class="container-index-dashboard">
  <div class="card-form-dashboard">
    <div class="card-table">
      <h1>Demandes de Devis</h1>
      <table style="width:100%">
        <tr class="col-name">
          <th>Status</th>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Email</th>
          <th>Téléphone</th>
          <th>Adresse de la Prestation</th>
          <th>Service</th>
          <th></th>
          <th></th>
        </tr>
        <% @devis.each do |d|%>
          <tr>
            <td><% if d.status == "Pending"%>
              <%= "⏸" %>
            <% elsif d.status == "Done" %>
             <%= "✔️" %>
            <% else  %>
              <%=  "❌"%>
            <% end %>
            </td>

            <td><%= d.first_name %></td>
            <td><%= d.last_name %></td>
            <td><%= d.email %></td>
            <td><%= d.telephone %></td>
            <td><%= d.building_address %></td>
            <td><%= d.service_demande %></td>
            <td><%= link_to devi_path(d.id) do %>
              <i class="fas fa-info-circle", id='info'></i>
            <% end %></td>
            <td><%= link_to devi_destroy_path(d.id), method: :delete, data: { confirm: "Est-vous sûr?" } do %>
              <i class="fa fa-trash", id="trash"></i>
            <% end %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
  <%= render 'shared/footer' %>
</div>

app/views/devis/show.html.erb
<div class="container-all-dashboard" id="id-container-all">
  <%= render 'shared/navbar' %>
    <div class="container-index-dashboard">
   <div class="card-form">
      <h1>Devi nr. <%= @devi.id %></h1>
      <table style="width:100%">
        <tr class="col-name">
          <td>Status</td><td><%= @devi.status %></td>
        </tr>
        <tr class="col-name">
          <td>Nom</td><td><%= @devi.first_name %></td>
        </tr>
        <tr class="col-name">
          <td>Prénom</td><td><%= @devi.last_name %></td>
        </tr>
        <tr class="col-name">
          <td>Email</td><td><%= @devi.email %></td>
        </tr>
        <tr class="col-name">
          <td>Téléphone</td><td><%= @devi.telephone %></td>
        </tr>
        <tr class="col-name">
          <td>Address de la Prestation</td><td><%= @devi.building_address %></td>
        </tr>
        <tr class="col-name">
          <td>Passages/sem.</td><td><%= @devi.nr_de_passages %></td>
        </tr>
        <tr class="col-name">
          <td>Heures/sem.</td><td><%= @devi.nr_d_heures %></td>
        </tr>
        <tr class="col-name">
          <td>Cahier des Charges</td><td><%= @devi.cahier_de_charges %></td>
        </tr>
        <tr class="col-name">
          <td>Service</td><td><%= @devi.service_demande %></td>
        </tr>
        <tr class="col-name">
          <td>Date RDV</td><td><%= @devi.date_rdv %></td>
        </tr>
        <tr class="col-name">
          <td>Début Souhaité de la Préstation</td><td><%= @devi.date_debut_souhaitee%></td>
        </tr>
      </table>
      <div class="icons d-flex">
      <%= link_to devi_edit_path do %>
        <i class="far fa-edit" id="update"></i>
      <% end %>
      <%= link_to devis_index_path do %>
        <i class="fas fa-times" id="close"></i>
        <% end %>
      </div>
</div>
    </div>
  <%= render 'shared/footer' %>
</div>

app/views/pages/contact.html.erb
<!-- MOVED TO CONTACTS/NEW.HTML.ERB -->

app/views/pages/home.html.erb
<div class="container-all">
  <div class="container-logo">
    <div class="container-avatar">
      <%= image_tag("color-logo.png", :alt => "logosample feed", class: "avatar-large") %>
    </div>
    <div class="container-company-intro-info">
      <h1>CLEANING PRO SERVICES</h1>
      <h2>Le service de nettoyage à l'écoute de vos besoins.</h2>
    </div>
  </div>
<!--  <%= render './shared/flashes' %> -->
  <%= render 'shared/navbar' %>

  <div class="main-container">
    <div class="container-who d-flex align-items-center", id="who">
      <h1>Qui Sommes-Nous?</h1>
      <div class="container-who-details d-flex justify-content-center align-items-center">
        <div class="container-who-details-text col-12 col-md-6 col-lg-8">
          <p>Nous sommes une société qui existe depuis 2015 et qui a grandit petit à petit principalement via le bouche à oreilles.
             Chaque devis est analysé avec soin afin de pouvoir satisfaire un maximum les (futurs) clients.</p>
          <p>Nos clients actuels sont des copropriétés et des agences bancaires indépendantes. Vous pourrez trouver leurs avis sur notre travail dans la rubrique "L'Expérience Client".</p>
          <p>Notre entreprise essaie d’utiliser les produits écologiques à condition que ceux-ci soient aussi efficaces que les produits « classiques ». A efficacité égale, nous nous tournerons donc vers le produit écologique afin de répondre au mieux aux problématiques climatiques et sanitaires actuelles.</p>
          <cite>- Laurent Vanesse, Gérant G&A Cleaning Pro Services</cite>
        </div>
        <!-- <div class="container-who-details-text col-12 col-md-6 col-lg-4"> -->
          <div class="g-a-contact col-12 col-md-6 col-lg-4">
            <%= image_tag("logo_without_slogan.png", :alt => "logosample feed", class: "avatar-medium") %>
            <h4><strong>Cleaning Pro Services</strong></h4>
            <p>Nr de TVA: 0717771789</p>
            <p>55, Terkluizendreef</p>
            <p>1640 Sint-Genesius-Rode</p>
            <p>0485/13.03.38</p>
            <p>info@gacleaningproservices.com</p>
          </div>
      <!--   </div> -->
      </div>
    </div>
    <div class="container-services" id="services">
      <h1>Services Proposés</h1>
      <div class="container-listofservices d-flex flex-grow justify-content-center align-items-center">
        <div class="cards">
          <div class="card-service" id="service-1">
            <div class="card-service-inner">
              <div class="card-service-front">
                <%= image_tag "bureaux.jpg" %>
                <h3>Bureaux & Locaux Professionnels</h3>
              </div>
              <div class="card-service-back">
                <div class="service-details">
                  <%= link_to "Devis Gatuit", devis_path, id: "btn-ghost-card" %>
                  <h3>Bureaux & Locaux Professionnels</h3>
                  <p>G&A vous propose un nettoyage régulier ou ponctuel d’espace de travail. Présentez-nous vos besoins et nous pourrons définir ensemble un service à la carte qui convient le mieux à votre activité professionnelle.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="card-service" id="service-2">
            <div class="card-service-inner">
              <div class="card-service-front">
                <%= image_tag "copropriétés.jpg" %>
                <h3>Copropriétés & Espaces Communs</h3>
              </div>
              <div class="card-service-back">
                <div class="service-details">
                  <%= link_to "Devis Gatuit", devis_path, id: "btn-ghost-card" %>
                  <h3>Copropriétés & Espaces Communs</h3>
                  <p>G&A vous propose un service discret, rapide et efficace pour vous aider à entretenir copropriétés et espaces communs d'immeubles de logement.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="card-service" id="service-3">
            <div class="card-service-inner">
              <div class="card-service-front">
                <%= image_tag "wall-painting.jpg" %>
                <h3>Interventions Spécialisées</h3>
              </div>
              <div class="card-service-back">
                <div class="service-details">
                  <%= link_to "Devis Gatuit", devis_path, id: "btn-ghost-card" %>
                  <h3>Interventions Spécialisées</h3>
                  <p>Des travaux ont lieu dans vos bureaux et vous souhaitez un nettoyage professionnel pour remettre le tout en état? Besoin d'un petit raffraichissement de vos espaces communs? D'autres besoins? Parlez-nous en, et nous apporterons une solution à votre demande...</p>
                </div>
              </div>
            </div>
          </div>
          <div class="card-service" id="service-4">
            <div class="card-service-inner">
              <div class="card-service-front">
                <%= image_tag "entretien_espaces_verts.jpg"%>
                <h3>Entretien Espaces Verts</h3>
              </div>
              <div class="card-service-back">
                <div class="service-details">
                  <%= link_to "Devis Gatuit", devis_path, id: "btn-ghost-card" %>
                  <h3>Entretien Espaces Verts</h3>
                  <p>Vous souhaitez entretenir un espace vert dans votre copropriété ou lieu de travail, mais n'avez pas le temps ou le materiel adéquat? G&A peut s'en charger!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-clients-input d-flex align-items-center" id='clients'>
      <h1>L'Expérience Client</h1>
      <div class="card-input row col-12 col-lg-6">
        <div class="top-card d-flex align-items-center">
          <h2>Travaux de rafraîchissement et nettoyage</h2>
        </div>
        <div class="comment-card flex-grow">
          <p>Je devais raffraîchir un appartement suite à un changement de locataire.
            Entre les deux locations, il y avait un weekend seulement. J'ai fait appel à G&A,
            qui a réagit très arpidement: raffraîchissement des peintures pour 100m2 d'appartement,
            grand nettoyage de l'appartement (sol, armoires, vitres, portes, interrupteurs, SDB avec tous les sanitaires,
            cusine et tous les élecctroménagés, terrasse) et petite réparatition au niveau de l'écolement d'eau dans la
            cuisine. J'etais très satisfaite du service et mes nouveaux locataires ravis.
          </p>
          <cite>-Mme Morganti, Propriétaire</cite>
        </div>
      </div>
      <div class="card-input row col-12 col-lg-6">
        <div class="top-card d-flex align-items-center">
          <h2>Nettoyage de Copropriété</h2>
          </div>
          <div class="comment-card flex-grow">
            <p>G&A s'occupe de l'entretien courant du bâtiment où j'habite en tant que locataire.
              Il n'y a jamais eu de problèmes. Le personnel est très gentil, poli, ainsi qu'efficient et professionnel.
              C'est aussi beaucoup moins cher que ce que je payais avant.
            </p>
            <cite>-Mlle Impellizzeri, Locataire</cite>
          </div>
        </div>
      <%= link_to "Partager Votre Expérience", reviews_path, id: "btn-ghost-form" %>
            </div>
    </div>
  <%= render 'shared/footer' %>
</div>

app/views/reviews/index.html.erb
<div class="container-all-dashboard" id="id-container-all">
  <%= render 'shared/navbar' %>
  <div class="container-index-dashboard">
  <div class="card-form-dashboard">
    <div class="card-table">
      <h1>Revues des Clients</h1>
      <table style="width:100%">
        <tr class="col-name">
<!--           <th>Status</th> -->
          <th>Status</th>
          <th>Titre</th>
          <th>Contenu</th>
          <th>Rating</th>
          <th>Nom</th>
          <th>Role</th>
          <th></th>
          <th></th>
        </tr>
        <% @reviews.each do |r|%>
          <tr>
            <td><% if r.status == "Pending"%>
              <%= "⏸" %>
            <% elsif r.status == "Lu" %>
             <%= "👌" %>
            <% else  %>
              <%=  "⚠️"%>
            <% end %>
            </td>
            <!-- <td><i class="far fa-pause-circle"></i></td> -->
            <td><%= r.title %></td>
            <td><%= r.content %></td>
            <td><%= r.rating %></td>
            <td><%= r.writer %></td>
            <td><%= r.role %></td>
            <td><%= link_to review_path(r.id) do %>
              <i class="fas fa-info-circle", id='info'></i>
            <% end %></td>
            <!-- <td><i class="far fa-edit" id="update-icon"></i></td> -->
            <td><%= link_to review_destroy_path(r.id), method: :delete, data: { confirm: "Est-vous sûr?" } do %>
                  <i class="fa fa-trash", id="trash"></i>
                <% end %></td>
          </tr>
        <% end %>
      </table>
</div>
        </div>
        </div>
  <%= render 'shared/footer' %>
</div>

app/views/reviews/show.html.erb
<div class="container-all-dashboard" id="id-container-all">
  <%= render 'shared/navbar' %>
  <div class="container-index-dashboard">
  <div class="card-form">
<h1>Revue nr. <%= @review.id %></h1>
      <table style="width:100%">
        <tr class="col-name">
          <td>Status</td><td><%= @review.status %></td>
        </tr>
        <tr class="col-name">
          <td>Evaluation</td><td><%= @review.rating %></td>
        </tr>
        <tr class="col-name">
          <td>Contenu</td><td><%= @review.content %></td>
        </tr>
        <tr class="col-name">
          <td>Référence</td><td><%= @review.writer %></td>
        </tr>
        <tr class="col-name">
          <td>Role</td><td><%= @review.role %></td>
        </tr>
      </table>
      <div class="icons d-flex">
      <%= link_to review_edit_path do %>
        <i class="far fa-edit" id="update"></i>
      <% end %>
      <%= link_to reviews_index_path do %>
        <i class="fas fa-times" id="close"></i>
        <% end %>
      </div>
        </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar" id="navbar">
  <div class="sort-navbar d-flex justify-content-between align-items-center">
<!--     <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("color-logo-nobckgrd.png", :alt => "logosample feed", class: "avatar")  %>
    <% end %> -->


    <ul class="navbar-nav d-flex justify-content-end flex-row">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Demandes de Contacts", contacts_index_path, id: "nav-item" %>
          <%= link_to "Demandes de Devis", devis_index_path, id: "nav-item" %>
          <%= link_to "Liste des Revues", reviews_index_path, id: "nav-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, id: "nav-item" %>
          <%= image_tag("drums.jpg", class: "user-avatar") %>
        </li>
      <% else %>
        <li class="nav-item">
          <li class="nav-item d-flex align-items-center">
        <%= link_to "Accueil", root_path, id: "nav-item" %>
      </li>
        <li class="nav-item">
          <li class="nav-item d-flex align-items-center">
        <%= link_to "Qui sommes-nous?", '/#who', id: "nav-item" %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to "Nos services", '/#services', id: "nav-item" %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to "L'Expérience Client", '/#clients', id: "nav-item" %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to "Contact", contacts_path, id: "nav-item" %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to "Devis", devis_path, id: "nav-item" %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to "Log In", new_user_session_path, id: "btn-ghost" %>
      </li>
      <% end %>

    </ul>

  </div>
</div>